name: writr-build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install Dependencies
      run: yarn
    - name: Setting up Codecoverage
      run: yarn add codecov --global
    - name: Build    
      run: yarn build
    - name: Testing    
      run: yarn test
    - name: Updating Code Coverage    
      run: yarn coverage
