name: Writr Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install Dependencies
      run: yarn
    - name: Compile    
      run: yarn compile
    - name: Testing    
      run: yarn test
    - name: Updating Code Coverage
    - uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_KEY }}
